const $=s=>document.querySelector(s);
const T={
ss1:{s:'Social Studies',t:'Introduction to Society',m:15,d:'Easy',desc:'What society is, how communities form and why shared structures matter.',con:['What society means','Types of communities','How people interact','Why structures matter'],how:'Short visual explanation, simple examples, interactive cards and a reflection question.',act:'Sort real communities into family, school, neighbourhood and online groups.',
learn:[['Society','A society is a group of people who live together and share rules, places and ways of doing things.'],['Communities','A community is a smaller group inside society: a family, a school, a village, a club. Some form around place, others around interests.'],['Why structure matters','Roles, rules and shared values let people cooperate instead of colliding.']],ex:'Your school is a community. Students, teachers and staff have different roles, and shared rules keep the day running.',
chk:['What is one thing all communities have in common?',['People connected by something shared','A government building','A fixed size'],0,'Every community is built on people linked by a place, purpose or value.'],
quiz:[['What is a society?',['A group of people living and interacting together','A geographical location','A government building','A historical event'],0,'A society is people living and interacting under shared ways of life.'],['True or false: a school is a type of community.',['True','False'],0,'Schools bring people together around a shared purpose.'],['A new student learns the school rules and joins a club. What does this show?',['Social structures help people cooperate','Rules are unnecessary','Communities never change'],0,'Rules and roles help newcomers fit in and work with others.'],['Which is a community built on a shared interest?',['A chess club','A river','A calendar'],0,'A chess club forms because members share an interest.'],['Why do social structures matter?',['They help people live and work together','They stop people talking','They only matter in cities'],0,'Structures give people predictable ways to cooperate.']]},
ss2:{s:'Social Studies',t:'History & Change',m:60,d:'Medium',desc:'How we study the past through timelines, and how events shape the present.',con:['What history is','Why we study it','Timelines','Major events','Past to present'],how:'Interactive timeline, short explanations, historical cards and a What happened next? prompt.',act:'Place five events on a timeline, then predict what happened next.',
learn:[['History','History is the study of what happened in the past, using evidence such as records, objects and stories.'],['Timelines','A timeline puts events in order, so we can see what caused what.'],['Past shapes present','The printing press spread ideas faster, which helped schools and newspapers grow.']],ex:'Tap an event: the invention of the printing press (1440s). What happened next? Books became cheaper and more people learned to read.',
chk:['Why do we put events on a timeline?',['To see order and cause','To make them look neat','To memorise dates only'],0,'Order helps us see how one event led to another.'],
quiz:[['What is history?',['The study of the past using evidence','A list of future plans','A type of map','A kind of law'],0,'History uses evidence to understand the past.'],['True or false: past events can influence the present.',['True','False'],0,'Laws, borders and customs today all have roots in past events.'],['Which tool shows events in order?',['Timeline','Compass','Graph of prices'],0,'A timeline orders events over time.'],['Scenario: cheaper books lead to more readers. This is an example of...',['An event changing everyday life','A random coincidence','A geographic feature'],0,'One event can reshape how people live.'],['Why study history?',['To learn from the past and understand today','To avoid the present','To memorise names'],0,'History helps us understand why things are as they are.']]},
ss3:{s:'Social Studies',t:'Geography & Places',m:30,d:'Medium',desc:'Continents, countries, physical and human geography, and how place shapes life.',con:['Continents and countries','Physical geography','Human geography','Population'],how:'Map-style visual, location cards and short knowledge checks.',act:'Tap regions on the map and match each to how it shapes daily life.',
learn:[['Physical geography','Mountains, rivers, deserts and oceans: the natural features of Earth.'],['Human geography','Where people live, how they move and how they use land: cities, farms, roads.'],['Place shapes life','Rivers gave early cities water and trade routes. Mountains slowed travel.']],ex:'Tap a place: Nile Valley. A river in a desert meant farming was possible only near the water, so people settled along it.',
chk:['A river is part of which kind of geography?',['Physical','Human','Political only'],0,'Rivers are natural features.'],
quiz:[['How many continents are usually counted?',['Seven','Five','Nine'],0,'Seven continents are the common count.'],['True or false: a city is part of human geography.',['True','False'],0,'Cities are created by people.'],['Which is physical geography?',['A mountain range','A highway','A border checkpoint'],0,'Mountains are natural.'],['Why did early cities grow near rivers?',['Water and trade','Rivers are decorative','Mountains were unsafe only'],0,'Rivers gave water, food and routes.'],['Population means...',['The number of people living in a place','The size of a country','A type of climate'],0,'Population counts people.']]},
ss4:{s:'Social Studies',t:'Government & Civics',m:20,d:'Medium',desc:'Why governments exist, how they are organised and how citizens take part.',con:['What government is','Why it exists','Civic responsibilities','Levels of government','Participation'],how:'Visual diagrams, scenario questions and short interactive examples.',act:'Decide which level of government handles a local problem.',
learn:[['Government','A government makes and enforces rules and provides services for a community.'],['Levels','Local, state or regional, and national governments share different responsibilities.'],['Citizens','Citizens vote, follow laws, pay taxes and speak up about issues.']],ex:'A broken streetlight on your road is usually a local government matter. Defence is national.',
chk:['Who usually fixes a local road?',['Local government','Only national government','No one'],0,'Local roads are typically a local responsibility.'],
quiz:[['What does a government do?',['Makes and enforces rules, provides services','Only collects taxes','Only runs schools'],0,'Governments make rules and provide services.'],['True or false: voting is a way citizens take part.',['True','False'],0,'Voting is a core form of participation.'],['Scenario: your town needs a new park. Who decides first?',['Local government','Foreign government','A private club only'],0,'Local needs go to local government.'],['Which is a civic responsibility?',['Following laws','Ignoring rules','Avoiding all groups'],0,'Following laws keeps communities fair.'],['Why do governments exist?',['To organise communities and keep order','To replace families','To control weather'],0,'They coordinate services and order.']]},
ss5:{s:'Social Studies',t:'Economy & Everyday Life',m:25,d:'Easy',desc:'Needs, wants, production, consumption and how economies touch daily life.',con:['What an economy is','Needs vs wants','Production and consumption','Jobs and resources'],how:'Simple visuals, everyday examples and mini decision activities.',act:'Spend a small weekly budget on needs and wants.',
learn:[['Economy','An economy is how people make, share and use goods and services.'],['Needs vs wants','Needs keep us alive and well: food, shelter. Wants make life nicer: games, treats.'],['Producers and consumers','Producers make things. Consumers use them. Most of us are both.']],ex:'You have 100 coins: food is a need, a concert ticket is a want. You choose, and that choice is economics.',
chk:['Which is a need?',['Food','A new game','A concert ticket'],0,'Food is essential to live.'],
quiz:[['An economy is...',['How goods and services are made, shared and used','A type of government','A map'],0,'It is about making, sharing and using.'],['True or false: a want is essential for survival.',['True','False'],1,'Wants are nice to have, not essential.'],['Who is a consumer?',['Someone who uses a product','Only a factory owner','Only a farmer'],0,'Consumers use goods and services.'],['Scenario: you have limited money. What is the best first step?',['Cover needs first','Buy wants first','Spend everything'],0,'Needs come before wants.'],['Which is a resource?',['Water','A rumour','A holiday'],0,'Resources are inputs like water and land.']]},
sc1:{s:'Science',t:'Science Foundations',m:45,d:'Easy',desc:'How scientists observe, question and test ideas about the world.',con:['Observation','Hypotheses','Simple experiments'],how:'Short explanations and quick checks (prototype preview).',act:'Predict whether a ball or a book falls first, then reason.',
learn:[['Observe','Science starts by noticing something carefully.'],['Test','A fair test changes one thing at a time.']],ex:'Water two plants, one in sun and one in shade. Only light differs.',chk:['A fair test changes...',['One thing at a time','Everything','Nothing'],0,'Changing one variable shows its effect.'],
quiz:[['Science begins with...',['Observation','Guessing','Opinion'],0,'Careful observation.'],['True or false: a fair test changes many things at once.',['True','False'],1,'It changes one thing.']]},
ma1:{s:'Math',t:'Algebra Basics',m:30,d:'Medium',desc:'Use letters for unknown numbers and solve simple equations.',con:['Variables','Simple equations','Balancing both sides'],how:'Worked examples and quick checks (prototype preview).',act:'Keep a scale balanced while solving x + 3 = 8.',
learn:[['Variable','A letter such as x stands for a number we do not know yet.'],['Balance','Whatever you do to one side of an equation, do to the other.']],ex:'x + 3 = 8. Subtract 3 from both sides, so x = 5.',chk:['If x + 2 = 5, what is x?',['3','7','2'],0,'5 minus 2 is 3.'],
quiz:[['If x + 4 = 9, x is...',['5','13','4'],0,'9 minus 4.'],['True or false: you must do the same to both sides.',['True','False'],0,'That keeps the equation balanced.']]}};
const SUBJ=[{k:'Science',cat:'Science',id:'sc1',desc:'Explore how the world works through scientific concepts, observations and experiments.'},{k:'Math',cat:'Mathematics',id:'ma1',desc:'Build mathematical thinking through concepts, problem solving and practical applications.'},{k:'Social',cat:'Social Studies',id:'ss1',desc:'Understand society, history, geography, people and the systems that shape everyday life.'}];
const SS=['ss1','ss2','ss3','ss4','ss5'];
const st={grade:0,sk:'',avail:60,bag:[],plan:null,seen:new Set(),done:{},mins:0,page:'home',cur:'ss1',ang:0,S:null};
const fmt=m=>m<60?m+' min':Math.floor(m/60)+' hr'+(m%60?' '+m%60+' min':'');
const load=()=>st.bag.reduce((a,b)=>a+b.today,0);
const toast=t=>{const e=$('#toast');e.textContent=t;e.className='s';clearTimeout(toast.t);toast.t=setTimeout(()=>e.className='',2000)};
const inBag=id=>st.bag.some(b=>b.id===id);
function add(id){if(inBag(id))return toast('Already in your bag');st.bag.push({id,today:T[id].m,tom:0});st.seen.add(T[id].s);toast('Added to your Learning Bag');nav();if(st.page==='bag')go('bag')}
function rem(id){st.bag=st.bag.filter(b=>b.id!==id);go('bag')}
function nav(){const n=st.bag.length,p=st.page;const l=(k,t)=>`<button class="b ${p===k?'on':''}" onclick="go('${k}')">${t}</button>`;
$('#nav').innerHTML=`<div class="logo" onclick="go('home')"><svg width="30" height="30" viewBox="0 0 30 30" fill="none" stroke="#6B43D6" stroke-width="2"><path d="M15 5v18M8 24h14M5 11l10-3 10 3"/><path d="M2 17l3-6 3 6a3.5 3.5 0 01-6 0zM22 17l3-6 3 6a3.5 3.5 0 01-6 0z" stroke="#405CFF"/></svg>BALANCE-ED</div>${l('home','Market')}${l('bag','My Learning Bag'+(n?' ('+n+')':''))}${l('progress','Progress')}${l('signup','Sign up')}${l('login','Log in')}`}
function go(pg,a){st.page=pg;if(a)st.cur=a;nav();const f={home,stall,subject,detail,social,bag,plan,session,progress,login:()=>auth('login'),signup:()=>auth('signup')}[pg];$('#app').innerHTML=`<div class="pg">${f()}</div>`;scrollTo(0,0);if(pg==='bag')setScale()}
const ill=k=>`<svg width="90" height="60" viewBox="0 0 90 60" fill="none" stroke-width="2">${k==='Science'?'<circle cx="45" cy="30" r="8" fill="#F0EAFF" stroke="#6B43D6"/><ellipse cx="45" cy="30" rx="34" ry="12" stroke="#405CFF"/>':k==='Math'?'<path d="M14 50L44 10l30 40z" fill="#F0EAFF" stroke="#6B43D6"/><circle cx="66" cy="18" r="9" stroke="#405CFF"/>':'<circle cx="25" cy="38" r="9" stroke="#6B43D6"/><circle cx="65" cy="38" r="9" stroke="#405CFF"/><circle cx="45" cy="14" r="9" fill="#F0EAFF" stroke="#6B43D6"/><path d="M38 20l-8 10M52 20l8 10M34 40h22" stroke="#E2D8F5"/>'}</svg>`;
function setAvail(m){st.avail=m;go('home')}
function veg(k,z=56){const g='#5FA35B',m={tomato:`<circle cx="30" cy="35" r="20" fill="#D9503F"/><path d="M20 18l10 6 10-6-4 9H24z" fill="${g}"/>`,carrot:`<path d="M18 22l30 8-24 22z" fill="#F08A3C" transform="rotate(-20 30 30)"/><path d="M14 20l-6-10 8 4 2-8 4 9z" fill="${g}"/>`,broccoli:`<circle cx="20" cy="24" r="11" fill="${g}"/><circle cx="34" cy="20" r="12" fill="#4B8C4A"/><circle cx="42" cy="30" r="9" fill="${g}"/><path d="M26 32h8l2 22H24z" fill="#9BC48F"/>`,eggplant:`<ellipse cx="30" cy="36" rx="15" ry="20" fill="#6B43D6" transform="rotate(15 30 36)"/><path d="M22 14h16l-4 8H26z" fill="${g}"/>`,pea:`<path d="M8 38q22-30 44-8-22 16-44 8z" fill="${g}"/><circle cx="20" cy="34" r="4" fill="#CFE8BF"/><circle cx="30" cy="32" r="4" fill="#CFE8BF"/><circle cx="40" cy="32" r="4" fill="#CFE8BF"/>`,beet:`<circle cx="30" cy="38" r="17" fill="#8E3B6E"/><path d="M30 55l-2 4M30 21l-8-12M30 21l4-14" stroke="${g}" stroke-width="3" fill="none"/>`};return`<svg width="${z}" height="${z}" viewBox="0 0 60 60">${m[k]}</svg>`}
const GR=[[3,'tomato','carrot','pea'],[4,'carrot','beet','tomato'],[5,'broccoli','eggplant','tomato'],[6,'eggplant','pea','beet'],[7,'beet','broccoli','carrot'],[8,'pea','tomato','eggplant']];
function pickG(g){st.grade=g;go('stall')}
function home(){const o=[[30,'30 min'],[60,'1 hr'],[120,'2 hr'],[180,'3 hr'],[240,'3+ hrs']];
return`<div style="position:relative;overflow:hidden"><div class="awn"></div><section class="wrap hero" style="padding-top:32px"><div><div class="eye">A Learning Capacity Tool</div><h1>Shop for what you can learn today.</h1><p class="sub">Welcome to the learning market. Walk to your grade's stall, pick fresh subjects and topics, and weigh your bag against the time you actually have.</p>
<p style="font-weight:500;margin-top:24px">How much time do you have to shop?</p><div class="row">${o.map(x=>`<button class="b ${st.avail===x[0]?'on':''}" onclick="setAvail(${x[0]})">${x[1]}</button>`).join('')}</div>
<div class="row" style="margin-top:20px"><button class="b d" onclick="document.getElementById('sub').scrollIntoView({behavior:'smooth'})">Explore topics</button><button class="b" onclick="go('bag')">My Learning Bag</button></div></div>
<svg viewBox="0 0 400 300" style="width:100%;max-width:440px;justify-self:center" fill="none"><rect x="20" y="20" width="360" height="270" rx="40" fill="#F0EAFF"/><rect x="60" y="190" width="280" height="80" rx="10" fill="#EBD3AA" stroke="#C29B62" stroke-width="3"/><path d="M60 215h280M60 240h280" stroke="#C29B62" stroke-width="2"/><g style="animation:bob 3s ease-in-out infinite"><path d="M110 60h180l14 40H96z" fill="#6B43D6"/><path d="M110 60h30l-8 40h-30zM170 60h30l-2 40h-30zM230 60h30l4 40h-30z" fill="#fff"/></g><g transform="translate(90 130)">${veg('tomato',70)}</g><g transform="translate(160 118)">${veg('broccoli',80)}</g><g transform="translate(240 130)">${veg('eggplant',70)}</g></svg></section>
<i class="leaf" style="left:8%;top:0"><svg width="18" height="18" viewBox="0 0 20 20"><path d="M2 18C2 6 10 2 18 2 18 12 12 18 2 18z" fill="#5FA35B"/></svg></i><i class="leaf" style="left:52%;top:0;animation-delay:3s"><svg width="14" height="14" viewBox="0 0 20 20"><path d="M2 18C2 6 10 2 18 2 18 12 12 18 2 18z" fill="#5FA35B"/></svg></i></div>
<section class="lav" id="sub"><div class="wrap"><div class="eye">Pick your crate</div><h2>Choose your grade</h2><p class="sub">Each crate holds the subjects for one grade. Pick yours to walk to that stall.</p>
<div class="crates">${GR.map(g=>`<button class="crate ${st.grade===g[0]?'on':''}" onclick="pickG(${g[0]})"><div class="pile">${g.slice(1).map(v=>veg(v,52)).join('')}</div><b>Grade ${g[0]}</b><span class="mono">${g[0]===5?'Fully stocked · 3 subjects':'Restocking soon'}</span></button>`).join('')}</div></div></section>`}
function stall(){const g=st.grade||5,full=g===5;
if(!full)return`<section class="wrap"><button class="b" onclick="go('home')">Back to the market</button><div class="sign"><h2 style="margin:0">Grade ${g} stall</h2></div><div class="card" style="max-width:520px"><h3>Restocking today</h3><p class="sub">This stall is not open in the prototype yet. Grade 5 is fully stocked.</p><div class="row"><button class="b d" onclick="pickG(5)">Visit Grade 5</button></div></div></section>`;
return`<section class="wrap"><button class="b" onclick="go('home')">Back to the market</button><div class="eye" style="margin-top:28px">Grade 5</div><div class="sign"><h1 style="margin:0;font-size:clamp(32px,6vw,56px)">Grade 5 stalls</h1></div><p class="sub">Three subject stalls are open. Browse a stall, then add topics to your Learning Bag.</p>
<div class="grid3">${SUBJ.map((s,i)=>{const ids=s.k==='Social'?SS:[s.id];return`<div class="stall"><div class="awn"></div><div class="pile">${veg(['tomato','broccoli','eggplant'][i],64)}${veg(['carrot','pea','beet'][i],56)}</div><h3>${s.k.toUpperCase()}</h3><p class="mono" style="margin:0">${s.cat} · ${ids.length} topic${ids.length>1?'s':''}</p><p class="sub" style="margin:6px 0">${s.desc}</p><div class="row"><button class="b" onclick="go('subject','${s.k}')">Browse topics</button><button class="b d" onclick="add('${ids[0]}')">Add to bag</button></div></div>`}).join('')}</div></section>`}
function subject(){const k=st.cur;st.sk=k;const s=SUBJ.find(x=>x.k===k),ids=k==='Social'?SS:[s.id];st.seen.add(s.cat);
return`<section class="wrap"><button class="b" onclick="go('stall')">Back to Grade 5 stalls</button><div class="eye" style="margin-top:28px">Grade 5 · ${s.cat}</div><h1>${k==='Social'?'Social Studies':k}</h1><p class="sub">${k==='Social'?'Understand the people, places and systems that shape our world.':s.desc}</p><div class="list">${ids.map((id,i)=>{const t=T[id],d=st.done[id];return`<div class="mod"><div class="n">${veg(VEGL[(i+k.length)%6],40)}</div><div><h3 style="margin:0;font-size:22px">${t.t}</h3><p class="sub" style="margin:2px 0 6px">${t.desc}</p><span class="mono">${fmt(t.m)} · ${t.d}${d!=null?' · done '+d+'/'+t.quiz.length:''}</span></div><div class="row"><button class="b" onclick="go('detail','${id}')">View details</button><button class="b d" onclick="add('${id}')">Add to bag</button></div></div>`}).join('')}</div></section>`}
const VEGL=['tomato','carrot','broccoli','eggplant','pea','beet'];
function detail(){const id=st.cur,t=T[id];st.seen.add(t.s);const ss=SS.includes(id);
return`<section class="wrap"><button class="b" onclick="go('subject','${st.sk||'Social'}')">Back to topics</button><div class="eye" style="margin-top:32px">${t.s}</div><h1 style="font-size:clamp(36px,6vw,60px)">${t.t}</h1><div class="row"><span class="tag">${t.d}</span><span class="tag">${fmt(t.m)}</span><span class="tag">Quiz: ${t.quiz.length} questions</span></div><p class="sub" style="margin-top:16px">${t.desc}</p>
<div class="two" style="margin-top:24px"><div class="card"><h3>What you will learn</h3><ul>${t.con.map(c=>`<li>${c}</li>`).join('')}</ul></div><div class="card"><h3>How you will learn</h3><p>${t.how}</p><h3>Example activity</h3><p>${t.act}</p></div></div>
<div class="row" style="margin-top:24px"><button class="b d" onclick="add('${id}')">Add to bag</button><button class="b" onclick="start('${id}')">Start learning</button></div></section>`}
function social(){st.seen.add('Social Studies');
return`<section class="wrap"><button class="b" onclick="go('home')">Back to topics</button><div class="eye" style="margin-top:32px">Social Studies</div><h1>Social Studies</h1><p class="sub">Understand the people, places and systems that shape our world.</p><div class="list">${SS.map((id,i)=>{const t=T[id],d=st.done[id];return`<div class="mod"><div class="n">0${i+1}</div><div><h3 style="margin:0;font-size:22px">${t.t}</h3><p class="sub" style="margin:2px 0 6px">${t.desc}</p><span class="mono">${fmt(t.m)} · ${t.d}${d!=null?' · done '+d+'/'+t.quiz.length:''}</span></div><div class="row"><button class="b" onclick="go('detail','${id}')">View details</button><button class="b d" onclick="add('${id}')">Add to bag</button></div></div>`}).join('')}</div></section>`}
function scaleSVG(){return`<svg viewBox="0 0 400 250" style="width:100%;max-width:460px"><path d="M200 70v150M150 224h100" stroke="#6B43D6" stroke-width="5" stroke-linecap="round"/><g id="beam" style="transition:transform .9s cubic-bezier(.3,1.4,.5,1);transform-origin:200px 70px"><path d="M60 70h280" stroke="#171717" stroke-width="4" stroke-linecap="round"/><g id="pl" style="transition:transform .9s cubic-bezier(.3,1.4,.5,1);transform-origin:60px 70px"><path d="M60 70l-38 60h76zM22 130h76a38 22 0 01-76 0z" fill="#F0EAFF" stroke="#6B43D6" stroke-width="2"/><text x="60" y="122" text-anchor="middle" font-size="11" font-family="DM Mono" fill="#6B43D6">LOAD</text></g><g id="pr" style="transition:transform .9s cubic-bezier(.3,1.4,.5,1);transform-origin:340px 70px"><path d="M340 70l-38 60h76zM302 130h76a38 22 0 01-76 0z" fill="#fff" stroke="#405CFF" stroke-width="2"/><text x="340" y="122" text-anchor="middle" font-size="11" font-family="DM Mono" fill="#405CFF">TIME</text></g></g><circle cx="200" cy="70" r="9" fill="#6B43D6"/></svg>`}
function setScale(){const L=load(),A=st.avail,a=L?Math.max(-18,Math.min(18,-(L-A)/Math.max(L,A)*30)):0;const nb=a=>{const b=$('#beam');if(!b)return;b.style.transform=`rotate(${a}deg)`;$('#pl').style.transform=`rotate(${-a}deg)`;$('#pr').style.transform=`rotate(${-a}deg)`};nb(st.ang);requestAnimationFrame(()=>requestAnimationFrame(()=>{nb(a);st.ang=a}))}
function bag(){const L=load(),A=st.avail,over=L>A,n=st.bag.length,tom=st.bag.reduce((a,b)=>a+b.tom,0);
const cards=n?st.bag.map(b=>{const t=T[b.id];return`<div class="card"><span class="mono">${t.s}</span><h3 style="font-size:20px">${t.t}</h3><div class="row"><span class="tag">${fmt(b.today)} today</span><span class="tag">${t.d}</span>${b.tom?`<span class="tag">+${fmt(b.tom)} tomorrow</span>`:''}</div><div class="row"><button class="b" onclick="go('detail','${b.id}')">View details</button><button class="b d" onclick="rem('${b.id}')">Remove</button></div></div>`}).join(''):`<div class="card"><p>Your bag is empty.</p><button class="b" onclick="go('home')">Explore topics</button></div>`;
let msg='';if(n){msg=over?`<h2>Your bag is too heavy.</h2><p class="sub">You have selected more learning than you have time for today.</p><div class="row"><span class="tag">Remove a topic below</span><button class="b d" onclick="document.getElementById('split').scrollIntoView({behavior:'smooth'})">Split a topic</button></div>`:`<h2>Your learning is balanced.</h2><p class="sub">You have enough time for everything in your bag.</p><div class="row"><button class="b d" onclick="startPlan()">Start learning</button></div>`}
const big=st.bag.slice().sort((a,b)=>b.today-a.today)[0];
return`<section class="wrap"><h1 style="font-size:clamp(36px,6vw,64px)">Your Learning Bag</h1><p class="sub">Everything you picked, with its true time cost. Weigh it before you commit.</p><div class="grid3" style="grid-template-columns:repeat(auto-fill,minmax(250px,1fr))">${cards}</div></section>
<section class="lav"><div class="wrap two" style="align-items:center"><div style="text-align:center">${scaleSVG()}</div><div>${n?`<div class="row" style="gap:32px"><div><div class="mono">YOUR LEARNING LOAD</div><div class="big">${fmt(L)}</div></div><div><div class="mono">YOUR AVAILABLE TIME</div><div class="big">${st.avail===240?'3+ hrs':fmt(A)}</div></div></div>`:''}${msg}<div class="row" style="margin-top:14px">${[30,60,120,180,240].map(m=>`<button class="b ${A===m?'on':''}" onclick="setAvail2(${m})">${m===240?'3+ hrs':fmt(m)}</button>`).join('')}</div></div></div>
${over&&big?`<div class="wrap" id="split" style="padding-top:0"><div class="card"><div class="eye">Split learning</div><h3>${T[big.id].s} — ${T[big.id].t}</h3><p class="mono">Total ${fmt(big.today+big.tom)} · Available today ${fmt(Math.max(5,A-(L-big.today)))}</p><input type="range" id="sl" min="5" max="${big.today+big.tom}" step="5" value="${Math.min(big.today,Math.max(5,A-(L-big.today)))}" oninput="slv(${big.today+big.tom})"><div class="row" style="gap:32px"><div>Today <b id="st">–</b></div><div>Tomorrow <b id="sm">–</b></div></div><div class="row"><button class="b d" onclick="split('${big.id}')">Split &amp; balance</button></div></div></div>`:''}
${!over&&tom?`<div class="wrap" style="padding-top:0"><div class="card"><div class="eye">Balanced</div><p class="mono" style="margin:0">Today ${fmt(L)} · Tomorrow ${fmt(tom)}</p><button class="b" onclick="st.bag.forEach(b=>{b.today+=b.tom;b.tom=0});go('bag')">Learn tomorrow's part today</button></div></div>`:''}</section>${over?'<script>slv&&slv(0)<\/script>':''}`}
function setAvail2(m){st.avail=m;go('bag')}
function slv(tot){const s=$('#sl');if(!s)return;tot=+s.max;$('#st').textContent=fmt(+s.value);$('#sm').textContent=fmt(tot-s.value)}
function split(id){const b=st.bag.find(x=>x.id===id),v=+$('#sl').value,tot=b.today+b.tom;b.today=v;b.tom=tot-v;toast('Balanced');go('bag')}
setTimeout(()=>{},0);
const _go=go;go=function(p,a){_go(p,a);if(p==='bag')setTimeout(()=>slv(),30)};
function startPlan(){st.plan=st.bag.map(b=>({...b}));go('plan')}
function plan(){const p=st.plan||[],tot=p.reduce((a,b)=>a+b.today,0);
return`<section class="wrap"><div class="eye">Balanced</div><h1 style="font-size:clamp(36px,6vw,64px)">Today's Learning</h1><div class="list">${p.map((b,i)=>{const t=T[b.id];return`<div class="mod"><div class="n">${i+1}</div><div><h3 style="margin:0;font-size:20px">${t.s} — ${t.t}</h3><span class="mono">${fmt(b.today)}${st.done[b.id]!=null?' · complete':''}</span></div><div class="row"><button class="b d" onclick="start('${b.id}')">${st.done[b.id]!=null?'Review':'Start learning'}</button></div></div>`}).join('')}</div>
<div class="card" style="margin-top:24px"><div class="mono">TOTAL</div><div class="big">${fmt(tot)}</div><p class="sub" style="margin:0">${st.avail>=tot?fmt(st.avail-tot)+' remaining':'Over by '+fmt(tot-st.avail)}</p></div></section>`}
function start(id){st.S={id,step:0,qi:0,score:0,tried:false,fb:null};go('session')}
function pct(){const S=st.S,n=T[S.id].quiz.length;return S.step===0?10:S.step===1?25:S.step===2?40:S.step===3?40+Math.round(S.qi/n*55):100}
function session(){const S=st.S,t=T[S.id],q=t.quiz,labels=['Learn','Interact','Check','Quiz','Complete'];
const head=`<button class="b" onclick="go('${st.plan&&st.plan.some(x=>x.id===S.id)?'plan':SS.includes(S.id)?'social':'home'}')">Back to topics</button><div class="eye" style="margin-top:28px">${t.s} · ${SS.includes(S.id)?'Module 0'+(SS.indexOf(S.id)+1):'Preview'}</div><h1 style="font-size:clamp(34px,6vw,60px)">${t.t}</h1><p class="mono">${t.m} min · ${t.d} · ${pct()}% complete</p><div class="bar"><i style="width:${pct()}%"></i></div><div class="steps">${labels.map((l,i)=>`<span class="${i===S.step?'a':''}">${l}</span>`).join('')}</div>`;
let body='';
if(S.step===0)body=t.learn.map(l=>`<div class="def"><b>${l[0]}</b><br>${l[1]}</div>`).join('')+`<button class="b d" onclick="nx()">Continue</button>`;
else if(S.step===1)body=`<div class="card"><div class="eye">Example</div><p style="font-size:19px">${t.ex}</p></div><div class="row" style="margin-top:16px"><button class="b" onclick="S0(-1)">Back to topics</button><button class="b d" onclick="nx()">Continue</button></div>`.replace("S0(-1)","st.S.step=0;go('session')");
else if(S.step===2){const c=t.chk;body=`<div class="card"><div class="eye">Quick check</div><h3 style="font-size:22px">${c[0]}</h3>${c[1].map((o,i)=>`<button class="b opt ${S.fb!=null&&i===c[2]?'ok':''}" onclick="ans(${i})">${o}</button>`).join('')}${S.fb!=null?`<div class="fb"><b>${S.fb===c[2]?'Correct!':'Not quite. Try again.'}</b> ${c[3]}</div>`:''}</div>${S.fb===c[2]?'<div class="row" style="margin-top:16px"><button class="b d" onclick="nx()">Take quiz</button></div>':''}`}
else if(S.step===3){const c=q[S.qi];body=`<div class="card"><div class="eye">Question ${S.qi+1} of ${q.length}</div><h3 style="font-size:22px">${c[0]}</h3>${c[1].map((o,i)=>`<button class="b opt ${S.fb!=null?(i===c[2]?'ok':i===S.fb?'no':''):''}" onclick="ans(${i})">${'ABCD'[i]}. ${o}</button>`).join('')}${S.fb!=null?`<div class="fb"><b>${S.fb===c[2]?'Correct!':'Not quite. Try again.'}</b> ${c[3]}</div>`:''}</div>${S.fb===c[2]?`<div class="row" style="margin-top:16px"><button class="b d" onclick="nq()">${S.qi+1<q.length?'Continue':'Submit answers'}</button></div>`:''}`}
else body=`<div class="card" style="text-align:center;padding:48px 24px"><div class="big">${S.score} / ${q.length} Correct</div><h2 style="margin-top:12px">Session complete</h2><p class="sub" style="margin:0 auto 16px">Your progress has been saved.</p><div class="row" style="justify-content:center"><button class="b d" onclick="go('${st.plan&&st.plan.length?'plan':'progress'}')">Continue learning</button><button class="b" onclick="go('progress')">Progress</button></div></div>`;
return`<section class="wrap" style="max-width:760px">${head}${body}</section>`}
function nx(){st.S.step++;st.S.fb=null;go('session')}
function ans(i){const S=st.S;if(S.fb!=null&&S.fb===(S.step===2?T[S.id].chk[2]:T[S.id].quiz[S.qi][2]))return;S.fb=i;if(S.step===3&&!S.tried){S.tried=true;if(i===T[S.id].quiz[S.qi][2])S.score++}go('session')}
function nq(){const S=st.S;S.qi++;S.fb=null;S.tried=false;if(S.qi>=T[S.id].quiz.length){S.step=4;if(st.done[S.id]==null)st.mins+=T[S.id].m;st.done[S.id]=Math.max(st.done[S.id]||0,S.score);st.seen.add(T[S.id].s)}go('session')}
function progress(){const ssd=SS.filter(i=>st.done[i]!=null).length,c=Object.keys(st.done).length;
return`<section class="wrap"><h1 style="font-size:clamp(36px,6vw,64px)">Your Learning Progress</h1><p class="sub">A calm look at what you have learned. No rankings, just reflection.</p><div class="stats"><div class="card"><div class="mono">Subjects explored</div><div class="big">${st.seen.size}</div></div><div class="card"><div class="mono">Topics completed</div><div class="big">${c}</div></div><div class="card"><div class="mono">Learning time</div><div class="big">${st.mins?fmt(st.mins):'0 min'}</div></div><div class="card"><div class="mono">Current streak</div><div class="big">${c?1:0} day${c===1||!c?'':'s'}</div></div></div>
<div class="card"><h3>Social Studies</h3><p style="margin:0">${ssd} / 5 modules complete</p><div class="bar"><i style="width:${ssd*20}%"></i></div><p class="mono" style="margin:0">${fmt(SS.filter(i=>st.done[i]!=null).reduce((a,i)=>a+T[i].m,0))} learned</p><div class="row"><button class="b" onclick="go('social')">${ssd?'Continue':'Back to topics'}</button></div></div></section>`}
function auth(k){const su=k==='signup';
return`<section class="wrap"><div class="auth card" style="padding:36px"><div class="logo" style="margin:0 0 16px">BALANCE-ED</div><h2 style="font-size:34px">${su?'Create an account':'Welcome back'}</h2><label>Username<input type="text" id="u" autocomplete="off"></label><label>Password<input type="password" id="pw"></label>${su?'<label>Confirm password<input type="password" id="pw2"></label>':'<p><button class="b" style="border-color:transparent;padding-left:0" onclick="toast(\'Prototype: no reset needed\')">Forgot password?</button></p>'}<div class="row"><button class="b d" onclick="doAuth(${su})">${su?'Sign up':'Log in'}</button><button class="b" onclick="go('${su?'login':'signup'}')">${su?'Log in':'Sign up'}</button></div></div></section>`}
function doAuth(su){const u=$('#u').value.trim();if(!u)return toast('Enter a username');if(su&&$('#pw').value!==$('#pw2').value)return toast('Passwords do not match');toast(su?'Account created (prototype)':'Welcome back, '+u);go('home')}
go('home');
